- name: nfsサーバーを構築
  hosts:
    - target
  become: true
  vars:
    nfs_dir_path: /export/shared
    clients_ips:
      "{{ groups['clients'] }}"
  roles:
    - { role: install-server, tags: install-server }
- name: クライアントにnfs-commonをインストール
  hosts:
    - clients
  become: true
  tasks:
    - name: nfs-commonインストール
      ansible.builtin.apt:
        name: nfs-common
