- name: nfsサーバーを構築
  hosts:
    - target
  become: true
  vars_files:
    - ./roles/install-server/files/allowed_ports.yml 
  vars:
    nfs_dir_path: /export/shared
  roles:
    - { role: install-server, tags: install-server }
- name: クライアントにnfs-commonをインストール
  hosts:
    - clients
  become: true
  tasks:
    - name: nfs-commonインストール
      ansible.builtin.apt:
        name: nfs-common
